Add support for the QUIC protocol based connection method
ao-space/gt pull request #37
Opened 2023-09-24 15:41 UTC by DrakenLibra

Add support for the QUIC protocol based connection method.

2023-09-25 00:06 UTC, vyloy requested changes

2023-09-25 00:06 UTC, vyloy commented on server/conn.go
> +			remoteIP := strings.Split(remoteAddr, ":")[0]
这里可以兼容处理 IPv6 地址吗？

2023-09-25 00:06 UTC, vyloy commented on .github/workflows/container.yml
> +          ls -al release
这个文件是否只修改了行缩进？

2023-09-25 00:06 UTC, vyloy commented on client/client.go
> +			u.Host = net.JoinHostPort(u.Host, "10080")
请使用使用更广泛的默认值。

> Google's QUIC protocol uses User Datagram Protocol (UDP) over ports 80 and 443. Non-encrypted QUIC traffic uses UDP 80, and encrypted traffic is sent over UDP 443.

2023-09-25 00:06 UTC, vyloy commented on conn/quicConn.go
> +	key, err := rsa.GenerateKey(rand.Reader, 1024)
建议使用 ECC 系列算法

2023-09-26 14:48 UTC, DrakenLibra commented on server/conn.go
> +			remoteIP := strings.Split(remoteAddr, ":")[0]
已经修改，在最新的版本中已兼容。

2023-09-26 14:49 UTC, DrakenLibra commented on .github/workflows/container.yml
> +          ls -al release
是的，Goland打开文件后自动进行了缩紧。

2023-09-26 14:50 UTC, DrakenLibra commented on client/client.go
> +			u.Host = net.JoinHostPort(u.Host, "10080")
已经修改为433，并且修改了readme中相关内容。

2023-09-26 14:51 UTC, DrakenLibra commented on conn/quicConn.go
> +	key, err := rsa.GenerateKey(rand.Reader, 1024)
已经修改为ECC系列算法。并且支持用户自己选择certFile和keyFile。当用户自己未选择certFile和keyFile，则会调用函数利用ECC自动生成密钥和证书。

2023-09-27 01:34 UTC, vyloy commented on .github/workflows/container.yml
> +          ls -al release
那这个得还原，类似这样的修改不应该提交的。

2023-09-28 17:13 UTC, DrakenLibra commented on .github/workflows/container.yml
> +          ls -al release
已经还原

2023-09-28 17:14 UTC, DrakenLibra commented
#1

2023-10-09 01:26 UTC, vyloy requested changes

2023-10-09 01:26 UTC, vyloy commented on conn/quicConn.go
> +				panic(err)
不能遇到错误就直接 panic，需要把错误记录到日志，并选择是否需要返回上一级处理。

2023-10-31 00:38 UTC, vyloy approved these changes

2023-10-31 04:51 UTC, merged